# This is a basic workflow to help you get started with Actions

name: CI-Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [test_githubaction]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Define the operating system
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get OS
        run: ([System.Environment]::OSVersion)

      - name: Get PS Major Version
        run: $PSVersionTable.PSVersion.Major
